services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HTTP_RELATIVE_PATH=/auth
    volumes:
      - keycloak-data:/opt/keycloak/data
      - ./keycloak:/opt/keycloak/data/import:ro
    command: start-dev --import-realm
  api:
    build:
      context: src/api/.
      dockerfile: Dockerfile
    ports:
      - 5000:80
  frontend:
    build:
      context: src/frontend/.
      dockerfile: Dockerfile
    ports:
      - 4200:80

volumes:
  keycloak-data: